// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "sn", Type: field.TypeString},
		{Name: "gid", Type: field.TypeInt64},
		{Name: "uid", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:        "orders",
		Columns:     OrdersColumns,
		PrimaryKey:  []*schema.Column{OrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// SeckillGoodsColumns holds the columns for the "seckill_goods" table.
	SeckillGoodsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "goods_id", Type: field.TypeInt64},
		{Name: "seckill_price", Type: field.TypeFloat64, SchemaType: map[string]string{"mysql": "decimal(10,2)"}},
		{Name: "stock_count", Type: field.TypeInt64},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime},
	}
	// SeckillGoodsTable holds the schema information for the "seckill_goods" table.
	SeckillGoodsTable = &schema.Table{
		Name:        "seckill_goods",
		Columns:     SeckillGoodsColumns,
		PrimaryKey:  []*schema.Column{SeckillGoodsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// SeckillOrdersColumns holds the columns for the "seckill_orders" table.
	SeckillOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "order_id", Type: field.TypeInt64},
		{Name: "goods_id", Type: field.TypeInt64},
	}
	// SeckillOrdersTable holds the schema information for the "seckill_orders" table.
	SeckillOrdersTable = &schema.Table{
		Name:        "seckill_orders",
		Columns:     SeckillOrdersColumns,
		PrimaryKey:  []*schema.Column{SeckillOrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OrdersTable,
		SeckillGoodsTable,
		SeckillOrdersTable,
	}
)

func init() {
}
