// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/helloMJW/seckill/app/goods/service/internal/biz"
	"github.com/helloMJW/seckill/app/goods/service/internal/conf"
	"github.com/helloMJW/seckill/app/goods/service/internal/data"
	"github.com/helloMJW/seckill/app/goods/service/internal/server"
	"github.com/helloMJW/seckill/app/goods/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	goodsRepo := data.NewGoodsRepo(dataData, logger)
	goodsUsecase := biz.NewGoodsUsecase(goodsRepo, logger)
	goodsService := service.NewGoodsService(goodsUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, goodsService, logger)
	grpcServer := server.NewGRPCServer(confServer, goodsService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
