// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Goods is the predicate function for goods builders.
type Goods func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderGoods is the predicate function for ordergoods builders.
type OrderGoods func(*sql.Selector)
