// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/peter-wow/seckill/app/goods/service/internal/data/ent/ordergoods"
	"github.com/peter-wow/seckill/app/goods/service/internal/data/ent/predicate"
)

// OrderGoodsQuery is the builder for querying OrderGoods entities.
type OrderGoodsQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.OrderGoods
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrderGoodsQuery builder.
func (ogq *OrderGoodsQuery) Where(ps ...predicate.OrderGoods) *OrderGoodsQuery {
	ogq.predicates = append(ogq.predicates, ps...)
	return ogq
}

// Limit adds a limit step to the query.
func (ogq *OrderGoodsQuery) Limit(limit int) *OrderGoodsQuery {
	ogq.limit = &limit
	return ogq
}

// Offset adds an offset step to the query.
func (ogq *OrderGoodsQuery) Offset(offset int) *OrderGoodsQuery {
	ogq.offset = &offset
	return ogq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ogq *OrderGoodsQuery) Unique(unique bool) *OrderGoodsQuery {
	ogq.unique = &unique
	return ogq
}

// Order adds an order step to the query.
func (ogq *OrderGoodsQuery) Order(o ...OrderFunc) *OrderGoodsQuery {
	ogq.order = append(ogq.order, o...)
	return ogq
}

// First returns the first OrderGoods entity from the query.
// Returns a *NotFoundError when no OrderGoods was found.
func (ogq *OrderGoodsQuery) First(ctx context.Context) (*OrderGoods, error) {
	nodes, err := ogq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ordergoods.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ogq *OrderGoodsQuery) FirstX(ctx context.Context) *OrderGoods {
	node, err := ogq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrderGoods ID from the query.
// Returns a *NotFoundError when no OrderGoods ID was found.
func (ogq *OrderGoodsQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ogq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ordergoods.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ogq *OrderGoodsQuery) FirstIDX(ctx context.Context) int64 {
	id, err := ogq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrderGoods entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one OrderGoods entity is not found.
// Returns a *NotFoundError when no OrderGoods entities are found.
func (ogq *OrderGoodsQuery) Only(ctx context.Context) (*OrderGoods, error) {
	nodes, err := ogq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ordergoods.Label}
	default:
		return nil, &NotSingularError{ordergoods.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ogq *OrderGoodsQuery) OnlyX(ctx context.Context) *OrderGoods {
	node, err := ogq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrderGoods ID in the query.
// Returns a *NotSingularError when exactly one OrderGoods ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ogq *OrderGoodsQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ogq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ordergoods.Label}
	default:
		err = &NotSingularError{ordergoods.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ogq *OrderGoodsQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := ogq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrderGoodsSlice.
func (ogq *OrderGoodsQuery) All(ctx context.Context) ([]*OrderGoods, error) {
	if err := ogq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ogq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ogq *OrderGoodsQuery) AllX(ctx context.Context) []*OrderGoods {
	nodes, err := ogq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrderGoods IDs.
func (ogq *OrderGoodsQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := ogq.Select(ordergoods.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ogq *OrderGoodsQuery) IDsX(ctx context.Context) []int64 {
	ids, err := ogq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ogq *OrderGoodsQuery) Count(ctx context.Context) (int, error) {
	if err := ogq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ogq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ogq *OrderGoodsQuery) CountX(ctx context.Context) int {
	count, err := ogq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ogq *OrderGoodsQuery) Exist(ctx context.Context) (bool, error) {
	if err := ogq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ogq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ogq *OrderGoodsQuery) ExistX(ctx context.Context) bool {
	exist, err := ogq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrderGoodsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ogq *OrderGoodsQuery) Clone() *OrderGoodsQuery {
	if ogq == nil {
		return nil
	}
	return &OrderGoodsQuery{
		config:     ogq.config,
		limit:      ogq.limit,
		offset:     ogq.offset,
		order:      append([]OrderFunc{}, ogq.order...),
		predicates: append([]predicate.OrderGoods{}, ogq.predicates...),
		// clone intermediate query.
		sql:  ogq.sql.Clone(),
		path: ogq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrderID int64 `json:"order_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrderGoods.Query().
//		GroupBy(ordergoods.FieldOrderID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ogq *OrderGoodsQuery) GroupBy(field string, fields ...string) *OrderGoodsGroupBy {
	group := &OrderGoodsGroupBy{config: ogq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ogq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ogq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrderID int64 `json:"order_id,omitempty"`
//	}
//
//	client.OrderGoods.Query().
//		Select(ordergoods.FieldOrderID).
//		Scan(ctx, &v)
//
func (ogq *OrderGoodsQuery) Select(field string, fields ...string) *OrderGoodsSelect {
	ogq.fields = append([]string{field}, fields...)
	return &OrderGoodsSelect{OrderGoodsQuery: ogq}
}

func (ogq *OrderGoodsQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ogq.fields {
		if !ordergoods.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ogq.path != nil {
		prev, err := ogq.path(ctx)
		if err != nil {
			return err
		}
		ogq.sql = prev
	}
	return nil
}

func (ogq *OrderGoodsQuery) sqlAll(ctx context.Context) ([]*OrderGoods, error) {
	var (
		nodes = []*OrderGoods{}
		_spec = ogq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &OrderGoods{config: ogq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ogq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ogq *OrderGoodsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ogq.querySpec()
	return sqlgraph.CountNodes(ctx, ogq.driver, _spec)
}

func (ogq *OrderGoodsQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ogq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ogq *OrderGoodsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ordergoods.Table,
			Columns: ordergoods.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: ordergoods.FieldID,
			},
		},
		From:   ogq.sql,
		Unique: true,
	}
	if unique := ogq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ogq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ordergoods.FieldID)
		for i := range fields {
			if fields[i] != ordergoods.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ogq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ogq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ogq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ogq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ogq *OrderGoodsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ogq.driver.Dialect())
	t1 := builder.Table(ordergoods.Table)
	selector := builder.Select(t1.Columns(ordergoods.Columns...)...).From(t1)
	if ogq.sql != nil {
		selector = ogq.sql
		selector.Select(selector.Columns(ordergoods.Columns...)...)
	}
	for _, p := range ogq.predicates {
		p(selector)
	}
	for _, p := range ogq.order {
		p(selector)
	}
	if offset := ogq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ogq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrderGoodsGroupBy is the group-by builder for OrderGoods entities.
type OrderGoodsGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (oggb *OrderGoodsGroupBy) Aggregate(fns ...AggregateFunc) *OrderGoodsGroupBy {
	oggb.fns = append(oggb.fns, fns...)
	return oggb
}

// Scan applies the group-by query and scans the result into the given value.
func (oggb *OrderGoodsGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := oggb.path(ctx)
	if err != nil {
		return err
	}
	oggb.sql = query
	return oggb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (oggb *OrderGoodsGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := oggb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (oggb *OrderGoodsGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(oggb.fields) > 1 {
		return nil, errors.New("ent: OrderGoodsGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := oggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (oggb *OrderGoodsGroupBy) StringsX(ctx context.Context) []string {
	v, err := oggb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (oggb *OrderGoodsGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = oggb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ordergoods.Label}
	default:
		err = fmt.Errorf("ent: OrderGoodsGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (oggb *OrderGoodsGroupBy) StringX(ctx context.Context) string {
	v, err := oggb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (oggb *OrderGoodsGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(oggb.fields) > 1 {
		return nil, errors.New("ent: OrderGoodsGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := oggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (oggb *OrderGoodsGroupBy) IntsX(ctx context.Context) []int {
	v, err := oggb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (oggb *OrderGoodsGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = oggb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ordergoods.Label}
	default:
		err = fmt.Errorf("ent: OrderGoodsGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (oggb *OrderGoodsGroupBy) IntX(ctx context.Context) int {
	v, err := oggb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (oggb *OrderGoodsGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(oggb.fields) > 1 {
		return nil, errors.New("ent: OrderGoodsGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := oggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (oggb *OrderGoodsGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := oggb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (oggb *OrderGoodsGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = oggb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ordergoods.Label}
	default:
		err = fmt.Errorf("ent: OrderGoodsGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (oggb *OrderGoodsGroupBy) Float64X(ctx context.Context) float64 {
	v, err := oggb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (oggb *OrderGoodsGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(oggb.fields) > 1 {
		return nil, errors.New("ent: OrderGoodsGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := oggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (oggb *OrderGoodsGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := oggb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (oggb *OrderGoodsGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = oggb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ordergoods.Label}
	default:
		err = fmt.Errorf("ent: OrderGoodsGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (oggb *OrderGoodsGroupBy) BoolX(ctx context.Context) bool {
	v, err := oggb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (oggb *OrderGoodsGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range oggb.fields {
		if !ordergoods.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := oggb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (oggb *OrderGoodsGroupBy) sqlQuery() *sql.Selector {
	selector := oggb.sql
	columns := make([]string, 0, len(oggb.fields)+len(oggb.fns))
	columns = append(columns, oggb.fields...)
	for _, fn := range oggb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(oggb.fields...)
}

// OrderGoodsSelect is the builder for selecting fields of OrderGoods entities.
type OrderGoodsSelect struct {
	*OrderGoodsQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ogs *OrderGoodsSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ogs.prepareQuery(ctx); err != nil {
		return err
	}
	ogs.sql = ogs.OrderGoodsQuery.sqlQuery(ctx)
	return ogs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ogs *OrderGoodsSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ogs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ogs *OrderGoodsSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ogs.fields) > 1 {
		return nil, errors.New("ent: OrderGoodsSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ogs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ogs *OrderGoodsSelect) StringsX(ctx context.Context) []string {
	v, err := ogs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ogs *OrderGoodsSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ogs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ordergoods.Label}
	default:
		err = fmt.Errorf("ent: OrderGoodsSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ogs *OrderGoodsSelect) StringX(ctx context.Context) string {
	v, err := ogs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ogs *OrderGoodsSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ogs.fields) > 1 {
		return nil, errors.New("ent: OrderGoodsSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ogs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ogs *OrderGoodsSelect) IntsX(ctx context.Context) []int {
	v, err := ogs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ogs *OrderGoodsSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ogs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ordergoods.Label}
	default:
		err = fmt.Errorf("ent: OrderGoodsSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ogs *OrderGoodsSelect) IntX(ctx context.Context) int {
	v, err := ogs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ogs *OrderGoodsSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ogs.fields) > 1 {
		return nil, errors.New("ent: OrderGoodsSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ogs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ogs *OrderGoodsSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ogs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ogs *OrderGoodsSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ogs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ordergoods.Label}
	default:
		err = fmt.Errorf("ent: OrderGoodsSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ogs *OrderGoodsSelect) Float64X(ctx context.Context) float64 {
	v, err := ogs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ogs *OrderGoodsSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ogs.fields) > 1 {
		return nil, errors.New("ent: OrderGoodsSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ogs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ogs *OrderGoodsSelect) BoolsX(ctx context.Context) []bool {
	v, err := ogs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ogs *OrderGoodsSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ogs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ordergoods.Label}
	default:
		err = fmt.Errorf("ent: OrderGoodsSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ogs *OrderGoodsSelect) BoolX(ctx context.Context) bool {
	v, err := ogs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ogs *OrderGoodsSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ogs.sqlQuery().Query()
	if err := ogs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ogs *OrderGoodsSelect) sqlQuery() sql.Querier {
	selector := ogs.sql
	selector.Select(selector.Columns(ogs.fields...)...)
	return selector
}
