// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/helloMJW/seckill/app/order/service/internal/data/ent/predicate"
	"github.com/helloMJW/seckill/app/order/service/internal/data/ent/seckillorder"
)

// SeckillOrderDelete is the builder for deleting a SeckillOrder entity.
type SeckillOrderDelete struct {
	config
	hooks    []Hook
	mutation *SeckillOrderMutation
}

// Where adds a new predicate to the SeckillOrderDelete builder.
func (sod *SeckillOrderDelete) Where(ps ...predicate.SeckillOrder) *SeckillOrderDelete {
	sod.mutation.predicates = append(sod.mutation.predicates, ps...)
	return sod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sod *SeckillOrderDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sod.hooks) == 0 {
		affected, err = sod.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SeckillOrderMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sod.mutation = mutation
			affected, err = sod.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sod.hooks) - 1; i >= 0; i-- {
			mut = sod.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sod.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sod *SeckillOrderDelete) ExecX(ctx context.Context) int {
	n, err := sod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sod *SeckillOrderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: seckillorder.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: seckillorder.FieldID,
			},
		},
	}
	if ps := sod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sod.driver, _spec)
}

// SeckillOrderDeleteOne is the builder for deleting a single SeckillOrder entity.
type SeckillOrderDeleteOne struct {
	sod *SeckillOrderDelete
}

// Exec executes the deletion query.
func (sodo *SeckillOrderDeleteOne) Exec(ctx context.Context) error {
	n, err := sodo.sod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{seckillorder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sodo *SeckillOrderDeleteOne) ExecX(ctx context.Context) {
	sodo.sod.ExecX(ctx)
}
