// Code generated by entc, DO NOT EDIT.

package ordergoods

import (
	"time"
)

const (
	// Label holds the string label denoting the ordergoods type in the database.
	Label = "order_goods"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldGoodsID holds the string denoting the goods_id field in the database.
	FieldGoodsID = "goods_id"
	// FieldGoodsTitle holds the string denoting the goods_title field in the database.
	FieldGoodsTitle = "goods_title"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the ordergoods in the database.
	Table = "order_goods"
)

// Columns holds all SQL columns for ordergoods fields.
var Columns = []string{
	FieldID,
	FieldOrderID,
	FieldGoodsID,
	FieldGoodsTitle,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
