// Code generated by entc, DO NOT EDIT.

package ordergoods

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/peter-wow/seckill/app/goods/service/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOrderID), v))
	})
}

// GoodsID applies equality check predicate on the "goods_id" field. It's identical to GoodsIDEQ.
func GoodsID(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGoodsID), v))
	})
}

// GoodsTitle applies equality check predicate on the "goods_title" field. It's identical to GoodsTitleEQ.
func GoodsTitle(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGoodsTitle), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOrderID), v))
	})
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOrderID), v))
	})
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.OrderGoods {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldOrderID), v...))
	})
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.OrderGoods {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldOrderID), v...))
	})
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldOrderID), v))
	})
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldOrderID), v))
	})
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldOrderID), v))
	})
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldOrderID), v))
	})
}

// GoodsIDEQ applies the EQ predicate on the "goods_id" field.
func GoodsIDEQ(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGoodsID), v))
	})
}

// GoodsIDNEQ applies the NEQ predicate on the "goods_id" field.
func GoodsIDNEQ(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldGoodsID), v))
	})
}

// GoodsIDIn applies the In predicate on the "goods_id" field.
func GoodsIDIn(vs ...int64) predicate.OrderGoods {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldGoodsID), v...))
	})
}

// GoodsIDNotIn applies the NotIn predicate on the "goods_id" field.
func GoodsIDNotIn(vs ...int64) predicate.OrderGoods {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldGoodsID), v...))
	})
}

// GoodsIDGT applies the GT predicate on the "goods_id" field.
func GoodsIDGT(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldGoodsID), v))
	})
}

// GoodsIDGTE applies the GTE predicate on the "goods_id" field.
func GoodsIDGTE(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldGoodsID), v))
	})
}

// GoodsIDLT applies the LT predicate on the "goods_id" field.
func GoodsIDLT(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldGoodsID), v))
	})
}

// GoodsIDLTE applies the LTE predicate on the "goods_id" field.
func GoodsIDLTE(v int64) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldGoodsID), v))
	})
}

// GoodsTitleEQ applies the EQ predicate on the "goods_title" field.
func GoodsTitleEQ(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGoodsTitle), v))
	})
}

// GoodsTitleNEQ applies the NEQ predicate on the "goods_title" field.
func GoodsTitleNEQ(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldGoodsTitle), v))
	})
}

// GoodsTitleIn applies the In predicate on the "goods_title" field.
func GoodsTitleIn(vs ...string) predicate.OrderGoods {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldGoodsTitle), v...))
	})
}

// GoodsTitleNotIn applies the NotIn predicate on the "goods_title" field.
func GoodsTitleNotIn(vs ...string) predicate.OrderGoods {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldGoodsTitle), v...))
	})
}

// GoodsTitleGT applies the GT predicate on the "goods_title" field.
func GoodsTitleGT(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldGoodsTitle), v))
	})
}

// GoodsTitleGTE applies the GTE predicate on the "goods_title" field.
func GoodsTitleGTE(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldGoodsTitle), v))
	})
}

// GoodsTitleLT applies the LT predicate on the "goods_title" field.
func GoodsTitleLT(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldGoodsTitle), v))
	})
}

// GoodsTitleLTE applies the LTE predicate on the "goods_title" field.
func GoodsTitleLTE(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldGoodsTitle), v))
	})
}

// GoodsTitleContains applies the Contains predicate on the "goods_title" field.
func GoodsTitleContains(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldGoodsTitle), v))
	})
}

// GoodsTitleHasPrefix applies the HasPrefix predicate on the "goods_title" field.
func GoodsTitleHasPrefix(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldGoodsTitle), v))
	})
}

// GoodsTitleHasSuffix applies the HasSuffix predicate on the "goods_title" field.
func GoodsTitleHasSuffix(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldGoodsTitle), v))
	})
}

// GoodsTitleEqualFold applies the EqualFold predicate on the "goods_title" field.
func GoodsTitleEqualFold(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldGoodsTitle), v))
	})
}

// GoodsTitleContainsFold applies the ContainsFold predicate on the "goods_title" field.
func GoodsTitleContainsFold(v string) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldGoodsTitle), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OrderGoods {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OrderGoods {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OrderGoods {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OrderGoods {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OrderGoods(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrderGoods) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrderGoods) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrderGoods) predicate.OrderGoods {
	return predicate.OrderGoods(func(s *sql.Selector) {
		p(s.Not())
	})
}
